### ISSUE TITLE
Cross-Domain-Zugriff auf das RSS-Feed

### ISSUE THREAD

**Issue by DracoBlue** [University-of-Potsdam-MM/Freiraum.UP#22]
``` text
XMLHttpRequest cannot load http://www.uni-potsdam.de/presse/nachrichten-veranstaltungen/nachrichten/rs…html?type=100&tx_ttnews%5Bcat%5D=19&cHash=e21dadaca4fdba6072e32952e55c55e1. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://jquery.com' is therefore not allowed access.
```

wenn man auf http://jquery.com geht und dort:

``` javascript
$.ajax('http://www.uni-potsdam.de/presse/nachrichten-veranstaltungen/nachrichten/rss-feed-abonnieren.html?type=100&tx_ttnews%5Bcat%5D=19&cHash=e21dadaca4fdba6072e32952e55c55e1');
```

eingibt.

Idealweise schickt der uni-potsdam.de-Server Cross-Domainheader mit denen man das Feed abholen kann.

**Comment by DracoBlue** [comment]
@alekiy Kannst Du Dich darum kümmern?

**Comment by alekiy** [comment]
Anscheinend werden keine Proxys mehr verwendet, dafür wird entsprechend corssDomain gesetzt siehe https://github.com/University-of-Potsdam-MM/rooms/blob/master/static/js/models/BaseRssCollection.js#L67

@DracoBlue sind dir Proxys somit noch notwendig und könnten ggf. aufgeräumt werden?

**Comment by DracoBlue** [comment]
Nein. Das crossDomain sagt nur, dass es mit funktionierenden CORS-Headern klappen könnte.

Der Fehler ist weiterhin:

<img width="517" alt="bildschirmfoto 2016-01-18 um 22 17 50" src="https://cloud.githubusercontent.com/assets/35926/12403046/6c512d34-be31-11e5-8b39-fbd9db9e70bc.png">

    Access-Control-Allow-Origin: *

für die RSS-Feeds und dann sollte es klappen. Solange sind die Proxys leider nötig.
